site/jekyll/getting-started/tutorial.md, site/jekyll/guides/cassette.md, site/jekyll/guides/server-side-rendering.md, site/jekyll/index.md, src/React.Sample.Cassette/Views/Home/Index.cshtml, src/React.Sample.Mvc4/Views/Home/Index.cshtml, src/React/Resources/JSXTransformer.js, src/React/Resources/react-with-addons.js
=> Update to React 0.12.2

src/React/JsxTransformer.cs
JsxTransformer adds the file name to exception message, however it discards the inner exception details, like stack trace. By including the inner exception in the thrown exception object we don't loose any information.
Created again because original PR (https://github.com/reactjs/React.NET/pull/68) was made using wrong base branch.
=> JsxTransformer exception now includes whole inner exception, not only message

src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactComponent.cs, src/React.Core/ReactComponent.cs, src/React.Tests/Core/ReactComponentTest.cs, src/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
I often find myself wanting/needing to disabled server-side rendering during development in order to use the Chrome debugger for troubleshooting javascript syntax issues and various React bugs/errors. My current process is to manually write out the client-side initialization code and commenting out the server-side helper:
```
<div id='temp></div>
React.render(React.createElement(CommentsBox, {"someJson": "blobl"}), document.getElementById("temp"));
```
This PR adds a flag that let's us instruct ReactJS.NET to simply render the client-side initialization code which can easily be turned off (back to server-side + client-side mode) when done debugging/developing.
If you don't think this is appropriate or would prefer it be implemented differently, just let me know. 
jslatts
=> Add HtmlHelperExtension flag to turn off server side rendering

site/jekyll/getting-started/tutorial.md
Adds an OutputCache attribute the the Comments() action, to prevent IE
from aggressively caching the comments list. Otherwise IE will only show
the comments that were returned in the first request unless you refresh
the entire page.
Fixes #111
=> Disable caching of Comments() action

site/jekyll/guides/server-side-rendering.md, src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactComponent.cs, src/React.Core/ReactComponent.cs, src/React.Tests/Core/ReactComponentTest.cs, src/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
Added an optional parameter to the `Render` method of `IReactCompoment` interface with default value to true. This won't change the behavior of the existing applications. On the other hand gives the flexibility to not render the React data attributes during server side rendering if there is a need. Internally has implemented by calling `React.renderToStaticMarkup` method instead the default` React.renderToString`. I changed the corresponding method in `HtmlHelperExtensions` class. At last I didn't figure out how to make sure that my code lints. Is there a tool or something like this we have to execute? #127
=> Render react attributes

src/React.Core/ReactEnvironment.cs
Server-side calls should show up before their client-side counterparts, as server-side rendering runs first.
=> Switch the order of server and client-side console.log calls

src/React.AspNet/JsxFileSystem.cs, src/React.AspNet/React.AspNet.xproj, src/React.AspNet/project.json, src/React.Sample.Mvc6/React.Sample.Mvc6.xproj, src/React.Sample.Mvc6/Startup.cs, src/React.Sample.Mvc6/project.json
Include the required changes to use the latest, beta 5, version of asp.net 5
=> Upgrade to aspnet5 beta5 version

src/React.Tests/Core/BabelTransformerTests.cs
Change two `Assert.AreEqual()` calls to `StringAssert.EndsWith()`. This fixes the build.
=> Fix broken tests in BabelTransformerTests.cs

site/jekyll/getting-started/tutorial.md, site/jekyll/guides/server-side-rendering.md, src/React.Core/ReactComponent.cs, src/React.Sample.Owin/Content/Index.html, src/React.Sample.Owin/Content/Sample.jsx, src/React.Tests/Core/ReactComponentTest.cs
I updated `RenderJavaScript()` in `src/React.Core/ReactComponent.cs` to call `ReactDOM.render()` per the v0.14 update, and modified all instances in the markdown docs.
I also noticed the OWIN sample wasn't running properly so I fixed that too. :smile:
=> Change React.render() to ReactDOM.render()

src/React.Sample.Mvc4/Content/Sample.jsx, src/React.Sample.Mvc4/Controllers/HomeController.cs, src/React.Sample.Mvc4/Views/Home/Index.cshtml
adding vary by header on comments action
=> adding server side paging without javascript

src/React.Core/FileCacheHash.cs, src/React.Tests/Core/FileCacheHashTests.cs
Changing FileCacheHash to use a FIPS compliant algorithm for https://github.com/reactjs/React.NET/issues/182
=> Amend FileCacheHash for FIPS compliance by using SHA1 instead of MD5

src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactComponent.cs, src/React.Core/ReactComponent.cs, src/React.Tests/Core/ReactComponentTest.cs
Add possibility to add class to container tag.
=> ContainerClass

src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactEnvironment.cs, src/React.Core/ReactComponent.cs, src/React.Core/ReactEnvironment.cs, src/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
If no server-side rendering will occur on a page, for instance if
component render is called with clientOnly: true, it is
pointless to initialize a Javascript engine on the server. This allows the
consumer to easily disable all server side Javascript if the server is
under heavy load.
=> Allow Javascript engines to be bypassed entirely.

src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactEnvironment.cs, src/React.Core/ReactEnvironment.cs, src/React.Tests/Core/ReactEnvironmentTest.cs
This allows other threads to use available engines while other MVC actions are being processed during a page render.
=> Always return JS engine to pool after component render.

src/React.AspNet/project.json, src/React.Core/packages.config, src/React.Sample.Mvc6/project.json, src/wrap/React.Core/project.json
Right now there is a problem with nuget, when resolving xproj with dependencies that contents other dependencies that contents dependencies you have also as dependencies for the project itself, as it is having problems with finding the dlls you already downloaded.
The way I found to fix this was to delete the base dependencies that are going to be needed anyway for another dependency.
Fixes issue #269
=> Fixing duplicate dependencies

build.proj, src/React.AspNet/HtmlHelperExtensions.cs, src/React.AspNet/project.json, src/React.Sample.Mvc6/project.json, src/global.json
Changes from RC2 to RTM are minimal, so there shouldn't be that many problems
=> Updating .NET Core libraries from 1.0 RC2 to 1.0 RTM

src/.editorconfig, src/React.Core/Babel.cs, src/React.Tests/Core/BabelTransformerTests.cs
In reaction to issue [#299](https://github.com/reactjs/React.NET/issues/299) I have added a hash based check, which then only transpiles the .jsx file if it has actually changed. This shortens build times considerably.
=> Use file hash to check for file changes before transpiling (#299)

src/React.Core/Initializer.cs
In some instances (unknown cause) RuntimeLibrary names are lower case.
In this case they were failing to register with TinyIoC.
#353
=> Fixed a problem registering React assemblies with TinyIoC in some instances

src/React.AspNet/AspNetFileSystem.cs
I also encountered the same problem, this issue https://github.com/reactjs/React.NET/issues/355
When run ASPdotNET Core app on Windows, it's work well.
Running on Linux (as Docker) or macOS, relative path show "fullpath"
ex)
```
assumed: ~/js/tutorial.jsx
actual: /app/wwwroot/js/tutorial.jsx
```
I tested with tutorial code on Linux(Docker on Windows) microsoft/aspnetcore:1.0.1 and dot net core on Windows via Visual Studio.
When run on Linux, add nuget package  JavaScriptEngineSwitcher.Extentions.MsDependencyInjection and JavaScriptEngineSwitcher.Jint
thanks
=> Fixed a problem duplicated relativePath

site/jekyll/getting-started/tutorial.md, tutorial-code/wwwroot/js/tutorial.jsx
=> Server side rendering issue fix with Remarkable

src/.nuget/packages.config, src/React.sln, tests/React.Tests/Core/BabelTransformerTests.cs, tests/React.Tests/Core/FileCacheHashTests.cs, tests/React.Tests/Core/FileSystemBaseTests.cs, tests/React.Tests/Core/FileSystemExtensionsTest.cs, tests/React.Tests/Core/GuidExtensionsTests.cs, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs, tests/React.Tests/Core/JavaScriptEngineUtilsTests.cs, tests/React.Tests/Core/ReactComponentTest.cs, tests/React.Tests/Core/ReactEnvironmentTest.cs, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs, tests/React.Tests/Owin/EntryAssemblyFileSystemTests.cs, tests/React.Tests/project.json
xUnit is easier to use in newer versions of .NET Core, as NUnit hasn't been updated to support them yet.
=> Switch from NUnit to xUnit

src/React.Core/Exceptions/ReactEngineNotFoundException.cs, src/React.Core/JavaScriptEngineFactory.cs, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs
This is not a classic pull request, but rather a proposal to improve the React.NET. This improvement will allow to meet the expectations of following users: [dima117](https://github.com/reactjs/React.NET/issues/360#issuecomment-291054084), [dgpedro](https://github.com/reactjs/React.NET/issues/190#issuecomment-259102850), [luty81](https://github.com/reactjs/React.NET/issues/338#issuecomment-268811536), [malachib](https://github.com/reactjs/React.NET/issues/355#issue-192121039), [ORuban](https://github.com/reactjs/React.NET/issues/379#issue-210133864), [jyee117](https://github.com/reactjs/React.NET/issues/400#issuecomment-297812855) and [mattgross76](https://github.com/reactjs/React.NET/issues/410#issuecomment-302524022).
=> Added a ability to select the default JavaScript engine

build.proj, src/React.Core/IJavaScriptEngineFactory.cs, src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/React.Core.csproj, src/React.Core/ReactEnvironment.cs, src/React.MSBuild/AssemblyBindingRedirect.cs, src/React.MSBuild/MSBuildHost.cs, src/React.Sample.Cassette/React.Sample.Cassette.csproj, src/React.Sample.Cassette/Web.config, src/React.Sample.Cassette/packages.config, src/React.Sample.Mvc4/React.Sample.Mvc4.csproj, src/React.Sample.Mvc4/Web.config, src/React.Sample.Mvc4/packages.config, src/React.Sample.Mvc6/React.Sample.Mvc6.csproj, src/React.Sample.Webpack/React.Sample.Webpack.csproj, src/React.Sample.Webpack/Web.config, src/React.Sample.Webpack/packages.config, tests/React.Tests/Core/ReactEnvironmentTest.cs
Upgrades ReactJS.NET to use JSPool 3.0, and updates all JavaScriptEngineSwitcher dependencies to their latest versions
Also adds an assembly redirect hack for MSBuild so that it can correctly load `JavaScriptEngineSwitcher.Core` when `JavaScriptEngineSwitcher.V8` references an older version. Normally this would be done in `Web.config` or `app.config` as an assembly redirect, but that does not work in MSBuild. The only way to do it in MSBuild is to manually redirect the assembly.
=> Upgrade to JSPool 3.0

src/React.Core/React.Core.csproj
This fixes building within VS 2017 community.
node_modules can sometimes contain paths that are very long, which can
trigger an msbuild bug
https://github.com/Microsoft/msbuild/issues/406
=> Exclude node_modules

src/React.Core/JavaScriptEngineFactory.cs
See https://github.com/reactjs/React.NET/issues/341.
If the page gets created, it could be added in.
=> Removed dead (not-yet-alive?) byo-react link

dev-build.bat
Loops over the potential MSBuild.exe paths for all three, and runs with the first one. If one isn't found it complains.
Fixes #452.
=> Allowed Community, Enterprise, or Professional VS 2017 versions

global.json, src/React.AspNet.Middleware/AssemblyRegistration.cs, src/React.AspNet.Middleware/MemoryFileCacheCore.cs, src/React.AspNet.Middleware/React.AspNet.Middleware.csproj, src/React.AspNet/React.AspNet.csproj, src/React.Sample.Mvc6/Program.cs, src/React.Sample.Mvc6/React.Sample.Mvc6.csproj, src/React.Sample.Mvc6/Startup.cs
- Support for ASP.NET Core targeting .NET Framework to 4.6.1
- The use of .NET Standard 2.0 means .NET Framework is no longer required for React.AspNet and React.AspNet.Middleware
=> Update libraries for .NET Core to 2.0 and for .NET Standard to 2.0

build.proj, src/React.Router.Mvc4/React.Router.Mvc4.csproj, src/React.Router/HtmlHelperExtensions.cs, src/React.Router/ReactRouterComponent.cs, src/React.Router/ReactRouterException.cs, src/React.Router/SetServerResponse.cs, src/React.sln, tests/React.Tests/React.Tests.csproj
Upgrades `React.Router` to ASP.NET 2.0.
Also splits ASP.NET MVC 4 support out into a separate `React.Router.Mvc4` project. This is required as you can use both ASP.NET Core and "classic" ASP.NET from .NET Framework, so simply discriminating based on framework version is not sufficient, and it actually needs to be two separate packages.
cc @dustinsoftware
=> Upgrade React.Router to ASP.NET Core 2.0

src/React.Web/AspNetCache.cs, src/React.Web/AspNetFileSystem.cs, src/React.Web/AssemblyRegistration.cs
Sometimes, a user might wish to render HTML in an ASP.NET MVC web application outside of the context of a web request. An example would be email rendering in a separate thread. With the current implementations of `AspNetCache` and `AspNetFileSystem`, TinyIoC fails to inject the necessary objects because, internally, an `httpContext` is `null`.
For `AspNetCache`, we can obtain the cache from `HttpRuntime`, which `HttpContextBase` calls under the hood (as pointed out in the comments [here](http://www.hanselman.com/blog/UsingTheASPNETCacheOutsideOfASPNET.aspx)).
For `AspNetFileSystem`, `HttpServerUtilityBase` is used only for `.MapPath()`, which `HostingEnvironment` provides as a static method. This method [is slightly different](https://stackoverflow.com/questions/13441645/server-mappath-vs- …
=> Resolve ASP.NET environments without HTTP contexts

tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs, tests/React.Tests/React.Tests.csproj
Due to an xUnit bug, tests would attempt to run, but then fail
immediately. Updating the packages fixes the issue.
https://github.com/Microsoft/vstest/issues/811
=> Fix xUnit tests in VS2017

tests/React.Tests/Properties/AssemblyInfo.cs
This is caused by ConfigureMockEnvironment setting up the static
property Environment. Since tests run in parallel, there is a race
between which tests that set up different fake environments, causing
occasional failures. Disabling parallelization fixes the issue, and
tests run so fast that this should be ok.
=> Fix flakey tests

site/jekyll/guides/webpack.md
When using expose-loader with later versions of Webpack you need to keep -loader in the name like this:
`var Components = require('expose-loader?Components!./components'); `
instead of
`var Components = require('expose?Components!./components');`
This PR updates the docs with this change since most people needing this won't use Webpack 1.
=> Docs: Update expose-loader syntax for latest Webpack

src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactEnvironment.cs, src/React.Core/IReactSiteConfiguration.cs, src/React.Core/ReactSiteConfiguration.cs, src/React.Sample.Mvc4/Content/Sample.jsx, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
=> Add support for script nonce attributes

tutorial-code/tutorial-code.csproj
This was an oversight during the original .NET Core 2.0 port
=> Use NuGet reference for tutorial code

src/React.Router/ReactRouterComponent.cs
According to the documentation, as well as my testing,
React Router expects the URL supplied to `StaticRouter`
to be provided via the `location` prop name.
React.NET currently supplies this value via the
`path` prop name.
=> Replace "path" with "location" for SSR + React Router.

src/React.Core/ReactComponent.cs
=> Component name valid caching

src/React.AspNet/ActionHtmlString.cs, src/React.AspNet/HtmlHelperExtensions.cs, src/React.Web.Mvc4/React.Web.Mvc4.csproj, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
Native IHtmlContent/IHtmlString implementation
=> Native IHtmlContent/IHtmlString implementation

src/React.sln, tests/React.Tests.Benchmarks/Program.cs, tests/React.Tests.Benchmarks/React.Tests.Benchmarks.csproj, tests/React.Tests.Benchmarks/Sample.jsx
Useful for manually testing performance-related changes. This tool won't run during CI.
No worries if you can't get to reviewing this soon @Daniel15, just making sure the build passes. Without objection I'll merge in later this week.
=> Add benchmarking tool

site/jekyll/getting-started/tutorial_aspnet4.md
I had issues that many others have had with getting the server rendering of this tutorial to work out of the box. I came to realize that it was a discrepancy in the version of React being used on the client versus in the NuGet package. NuGet was using the latest, version 16, but the client side code all referenced version 15. All sorts of confusion and chaos ensued.
This is a major change but it boils down to a shift over to ES6 classes instead of the older `React.createClass()` method. I tested as I went along, so the code should all work. I did not update screenshots. I think any reasonably seasoned .NET developer will skip over those details anyway. I am not a seasoned .NET developer, and I had no issues with that side of things.
I also added a note at the bottom explaining how …
=> Updated the MVC tutorial for React 16

README.md, site/jekyll/getting-started/aspnetcore.md, site/jekyll/guides/chakracore.md, src/React.Sample.CoreMvc/React.Sample.CoreMvc.csproj, src/React.Sample.CoreMvc/Startup.cs, src/React.Sample.Router.CoreMvc/React.Sample.Router.CoreMvc.csproj, src/React.Sample.Router.CoreMvc/Startup.cs, tutorial-code/Startup.cs, tutorial-code/tutorial-code.csproj
Fixes #540 
`Startup.cs` in tutorial code was incorrectly using indentation with spaces, this PR fixes that as well
=> Add ChakraCore documentation

src/React.AspNet/ActionHtmlString.cs, src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactComponent.cs, src/React.Core/IReactEnvironment.cs, src/React.Core/ReactComponent.cs, src/React.Core/ReactEnvironment.cs, src/React.Router/ReactRouterComponent.cs, tests/React.Tests/Core/ReactComponentTest.cs, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
Hi, I wanted to submit my first open source PR for issue #521 for some review!
> Add ClientOnly as a property to ReactComponent. When ReactEnvironment.CreateComponent is called, ClientOnly needs to be set.
I believe I set this correctly in ReactEnvironment.cs on lines 305 and 307.  Since this is a new parameter for ReactComponent, do I need to go in and add the ClientOnly parameter to every call of ReactComponent?  Or should I set a default value?
> When RenderJavaScript is called in ReactComponent, ClientOnly should be checked. If true, ReactDOM.render should be written to the script instead of ReactDOM.hydrate.
I used a ternary operator for the conditional in ReactComponent.cs on line 236.  I saw ternary operators used in other parts of the codebase, is it appropriate to use here? …
=> Resolves Issue #521 Draft

src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/Resources/shims.js, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs
=> Fix crashes related to loading React 16.4.1

src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/Resources/shims.js, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs
`EnsureReactLoaded` uses this to print out which ones are missing.
Fixes #569.
=> Returned a list of missing globals in shims.js

src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/Resources/shims.js, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs
Hello!
The following [line of code](https://github.com/reactjs/React.NET/blob/83785cf9ea6cea01341ca023a32b4086d5a14cfb/src/React.Core/JavaScriptEngineFactory.cs#L188):
```csharp
var result = engine.CallFunction<string[]>("ReactNET_initReact");
```
Will always cause an error:
```
System.ArgumentException: The type of return value `System.String[]` is not supported.
```
This error occurs, because the JavaScript Engine Switcher only supports primitive types. Here is a quote from the documentation:
> The supported .NET types are as follows:
> 
>  * `JavaScriptEngineSwitcher.Core.Undefined`
>  * `System.Boolean`
>  * `System.Int32`
>  * `System.Double`
>  * `System.String`
This PR contains the simplest fix for this error.
=> Fix for the `EnsureReactLoaded` method of `React.JavaScriptEngineFactory` class

site/jekyll/_config.yml, site/jekyll/_layouts/default.html
There's some non-HTTPS URLs:
```
<meta property="og:url" content="http://reactjs.net/index.html" />
...
<link rel="alternate" type="application/rss+xml" title="ReactJS.NET" href="http://reactjs.net/feed.xml" />
```
This should fix it.
=> Fix insecure (non-HTTPS) links on site

src/React.AspNet.Middleware/AspNetFileSystem.cs, tests/React.Tests/Core/MiddlewareTests.cs, tests/React.Tests/React.Tests.csproj
Fixes #554 
It looks like this has never worked correctly with .NET Core...
JSPool looks for an exact match when a file changed event is raised, but we weren't first transforming the forwardslashes into backslashes.
=> Fix JS engine reloading in .NET Core

src/React.Web.Mvc4/React.Web.Mvc4.csproj
I think License info used to originally display in the README, and the former link would anchor down to it. This will take users to the correct place.
=> Update PackageLicenseUrl to point to LICENSE file

site/jekyll/features/css-in-js.md, site/jekyll/features/react-helmet.md, src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactComponent.cs, src/React.Core/IRenderFunctions.cs, src/React.Core/ReactComponent.cs, src/React.Core/RenderFunctions/EmotionFunctions.cs, src/React.Core/RenderFunctions/ReactHelmetFunctions.cs, src/React.Core/RenderFunctions/ReactJssFunctions.cs, src/React.Core/RenderFunctions/StyledComponentsFunctions.cs, src/React.Core/RenderFunctionsBase.cs, src/React.Router/HtmlHelperExtensions.cs, src/React.Router/ReactRouterComponent.cs, src/React.Router/ReactRouterFunctions.cs, src/React.Sample.Webpack.CoreMvc/Content/components/emotion.jsx, src/React.Sample.Webpack.CoreMvc/Content/components/expose-components.js, src/React.Sample.Webpack.CoreMvc/Content/components/home.jsx, src/React.Sample.Webpack.CoreMvc/Content/components/react-jss.jsx, src/React.Sample.Webpack.CoreMvc/Content/components/styled-components.jsx, src/React.Sample.Webpack.CoreMvc/Views/Home/Index.cshtml, src/React.Sample.Webpack.CoreMvc/Views/Shared/_Layout.cshtml, src/React.Sample.Webpack.CoreMvc/package-lock.json, src/React.Sample.Webpack.CoreMvc/package.json, tests/React.Tests/Core/ReactComponentTest.cs, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
This PR has some redundant commits.. another open PR should be merged first, but I can't do that until the github outage is over.
=> React helmet

netlify.toml
Noticed in #625 that we have a few missing redirects from old URLs.
=> Add some missing redirects

site/jekyll/features/css-in-js.md, site/jekyll/features/react-helmet.md, src/React.Core/RenderFunctions/ChainedRenderFunctions.cs, src/React.Core/RenderFunctions/EmotionFunctions.cs, src/React.Core/RenderFunctions/ReactHelmetFunctions.cs, src/React.Core/RenderFunctions/ReactJssFunctions.cs, src/React.Core/RenderFunctions/StyledComponentsFunctions.cs, src/React.Router/ReactRouterComponent.cs, src/React.Router/ReactRouterFunctions.cs, src/React.Sample.Webpack.CoreMvc/.babelrc, src/React.Sample.Webpack.CoreMvc/Content/components/expose-components.js, src/React.Sample.Webpack.CoreMvc/Content/components/react-jss.jsx, src/React.Sample.Webpack.CoreMvc/Views/Home/Index.cshtml, src/React.Sample.Webpack.CoreMvc/package-lock.json, src/React.Sample.Webpack.CoreMvc/package.json, tests/React.Tests/Core/ReactComponentTest.cs
It was always a bit clunky that the constructor was used for this. Now, there is a first-class ChainedRenderFunctions type that can be used to accomplish the same thing.
=> Improve chaining server-render helper functions

src/React.Core/ReactComponent.cs, tests/React.Tests/Core/ReactComponentTest.cs
=> Fix error calling hydrate instead of render when SSR disabled

src/React.Core/Exceptions/ReactScriptPrecompilationNotAvailableException.cs, src/React.Core/JavaScriptEnginePrecompilationUtils.cs, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs
If the script pre-compilation is not available, then throw an `ReactScriptPrecompilationNotAvailableException` exception.
=> Ensure availability of the script pre-compilation

src/React.Core/JavaScriptEngineUtils.cs
Not all engine-specific code was removed in the [“Remove auto-registered JS engines from React.Core”](https://github.com/reactjs/React.NET/commit/3281a16d6f3aee8c13f4f58d65baa6c915f95a5a) commit.
=> Remove remaining engine-specific code

src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/ReactComponent.cs, src/React.Core/ReactEnvironment.cs, tests/React.Tests/Core/JavaScriptEngineFactoryTest.cs
`JsScriptException` and `JsRuntimeException` classes cannot catch all errors that occur in JS engines (it is clearly seen from [exception hierarchy](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/How-to-upgrade-applications-to-version-3.X#reorganization-of-exceptions)), therefore `JsException` class should be used instead. Also, I removed a line and column numbers from error messages, because the original error messages already contain them.
Here are some examples of the original error messages:
```
------------------------------------------------------------
ChakraCoreJsEngine
------------------------------------------------------------
SyntaxError: Invalid character
at doc01.js:4:3 -> c @= 1;
------------------------------------------------------------
JintJsEngine …
```
=> Catch all the JavaScript Engine Switcher's exceptions

src/Cassette.React/Cassette.React.csproj, src/React.Core/React.Core.csproj, src/React.MSBuild/React.MSBuild.csproj, src/React.Sample.Cassette/React.Sample.Cassette.csproj, src/React.Sample.Cassette/packages.config, src/React.Sample.ConsoleApp/React.Sample.ConsoleApp.csproj, src/React.Sample.Mvc4/React.Sample.Mvc4.csproj, src/React.Sample.Mvc4/packages.config, src/React.Sample.Owin/React.Sample.Owin.csproj, src/React.Sample.Webpack.CoreMvc/React.Sample.Webpack.CoreMvc.csproj, tests/React.Tests.Benchmarks/React.Tests.Benchmarks.csproj, tests/React.Tests.Integration/React.Tests.Integration.csproj
Yesterday I released a [final version](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0) of the JavaScript Engine Switcher 3.0.0. This PR contains a simple upgrade of the JavaScript Engine Switcher's packages, and removing unnecessary dependency (System.Runtime.InteropServices.RuntimeInformation) from the React.Sample.Mvc4 project.
=> Update the JavaScript Engine Switcher to version 3.0.0

site/jekyll/getting-started/chakracore.md
When using ReactJS.NET version 4.0 with VroomJs now the following error occurs:
```
React.Core.Resources.react.generated.min.js: Uncaught ReferenceError: Set is not defined at line: 4 column: 69.
```
This error occurs because VroomJs is based on a very old version of V8 (version 3.17.16.2) that does not support modern ECMAScript. Therefore, it should be discarded, and use ChakraCore in the Mono runtime.
=> Add the Mono guide for ChakraCore

src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/JavaScriptEngineUtils.cs, src/React.Core/ReactEnvironment.cs, src/React.Core/ReactSiteConfiguration.cs
In some cases, information from the error message is not enough. Therefore, it is better to save original exceptions as inner exceptions.
=> Save original exceptions as inner exceptions

site/jekyll/getting-started/aspnetcore.md, site/jekyll/tutorials/aspnetcore.md
In tutorial did not specified that need to install the `JavaScriptEngineSwitcher.Extensions.MsDependencyInjection` package.
=> Fixes for ASP.NET Core Tutorial

renovate.json
Adds the following (separate) groupings:
- All packages from @Taritsyn's JavascriptEngineSwitcher repo
- All packages from https://github.com/aspnet/Extensions
- `Microsoft.AspNetCore*` packages plus those with source repo https://github.com/aspnet/MetaPackages or https://github.com/aspnet/AspNetCore
- `Microsoft.Owin*` packages
=> Add NuGet package groupings to Renovate Bot config

src/Cassette.React/Cassette.React.csproj, src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/React.Core.csproj, src/React.MSBuild/React.MSBuild.csproj, src/React.Sample.Cassette/React.Sample.Cassette.csproj, src/React.Sample.Cassette/Web.config, src/React.Sample.Cassette/packages.config, src/React.Sample.ConsoleApp/React.Sample.ConsoleApp.csproj, src/React.Sample.Mvc4/React.Sample.Mvc4.csproj, src/React.Sample.Mvc4/Web.config, src/React.Sample.Mvc4/packages.config, src/React.Sample.Owin/React.Sample.Owin.csproj, src/React.Sample.Webpack.CoreMvc/React.Sample.Webpack.CoreMvc.csproj, tests/React.Tests.Benchmarks/React.Tests.Benchmarks.csproj, tests/React.Tests.Integration/React.Tests.Integration.csproj
This will reduce the likelihood of problems such as [error #732](https://github.com/reactjs/React.NET/issues/732) “InvalidOperationException during JavaScriptEngineFactory.GetFactory”.
=> Reduce the time of using the enumerator of `JsEngineFactoryCollection` class

runs-msbuild.bat, src/React.Core/JavaScriptEngineFactory.cs, src/React.Core/Resources/babel-legacy/package-lock.json, src/React.Core/Resources/babel-legacy/package.json, src/React.Core/package-lock.json, src/React.Core/package.json, src/React.Router/ReactRouterFunctions.cs, src/React.Sample.Webpack.CoreMvc/Views/Home/Index.cshtml, src/React.Sample.Webpack.CoreMvc/package-lock.json, src/React.Sample.Webpack.CoreMvc/package.json
Hi guys, long time no see :)
There seems to be an error from at least 4.1.1 and onward (tried 4.2 and 5) which causes a null exception in 
React.Router.ReactRouterComponent.RenderRouterWithContext
line 69:
`JsonConvert.DeserializeObject<RoutingContext>(reactRouterFunctions.ReactRouterContext)`
This happens since when we disable SSR, ReactRouterFunctions never creates a context object in the js engine.
An extremely low effort quick fix follows, providing a default value for routerContext.
=> disabling ssr causes error in react router

build.proj, src/Cassette.React/Cassette.React.csproj, src/React.AspNet.Middleware/React.AspNet.Middleware.csproj, src/React.AspNet/React.AspNet.csproj, src/React.Core/React.Core.csproj, src/React.Core/Resources/babel-legacy/package-lock.json, src/React.Core/Resources/babel-legacy/package.json, src/React.Core/package-lock.json, src/React.Core/package.json, src/React.MSBuild/React.MSBuild.csproj, src/React.Owin/React.Owin.csproj, src/React.Router.Mvc4/React.Router.Mvc4.csproj, src/React.Router/React.Router.csproj, src/React.Sample.Webpack.CoreMvc/package-lock.json, src/React.Sample.Webpack.CoreMvc/package.json, src/React.Web.Mvc4/React.Web.Mvc4.csproj, src/React.Web/React.Web.csproj
NuGet finally has a symbol server and it's easy to generate and upload compatible symbols.
This minor change ensures that the symbols get generated. 
Per my experience and according to the docs they then get uploaded with the *.nupkg with nuget push.
I did notice issue https://github.com/reactjs/React.NET/issues/467 but was unable to verify that and will assume that functionality is currently broken.
See https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html for more info.
=> Nuget symbol server

src/React.AspNet/HtmlHelperExtensions.cs, src/React.Core/IReactComponent.cs, src/React.Core/ReactComponent.cs, src/React.Core/ReactEnvironment.cs, src/React.Router/ReactRouterComponent.cs, tests/React.Tests/Core/ReactComponentTest.cs, tests/React.Tests/Core/ReactEnvironmentTest.cs, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs, tests/React.Tests/Router/ReactRouterComponentTest.cs
Happy 4th! This addresses a year-old bug report in #543 
If you wanted to use output caching, it wasn't really feasible to use `Html.ReactWithInit` without introducing a render performance penalty, because your script tags had to all be added to the top of the page. This PR waits for the `DOMContentLoaded` event so that won't be an issue anymore. Calls to `Html.React` are unaffected.
=> Html.ReactWithInit improvements

build.proj, site/jekyll/_posts/2019-07-16-5.0.0-release.md
=> Blog post 5 0 0

.gitignore
These files are generated when we run `dev-build.bat`. They are kind of annoying when they keep showing in the change list.
=> ignore *.snupkg generated by  dev-build.bat

src/React.Template/reactnet-vanilla/tutorial-code.csproj
This typo was causing build failure because it points to a non-existent file.
=> Fix typo in tutorial-code.csproj

src/React.Router/ReactEnvironmentExtensions.cs, src/React.Router/ReactRouterComponent.cs, tests/React.Tests/Router/HtmlHelperExtensionsTest.cs, tests/React.Tests/Router/ReactRouterComponentTest.cs
PR for issue #1140 
The override of `RenderJavaScript` in `ReactRouterComponent` could be removed since they are the same. But leaving it as an option.
Hope it's ok :)
=> React.Router ReactDOM.hydrate with ClientOnly #1140

src/React.AspNet/HtmlHelperExtensions.cs
Couldn't compile with all the \<Compile Include="..\SharedAssemblyVersionInfo.cs" /> lines, since those files were missing, so had to remove those to test. 
Relevant changes are in the **src/React.AspNet/HtmlHelperExtensions.cs** file.
In short: the best solution to implement these changes would be to have access to an IUrlHelper instance.
Since we call **@Html.ReactGetScriptPaths()** inside a view, we can change this to **@Html.ReactGetScriptPaths(Url)**.
This way we can have access to the IUrlHelper.Content(...) method and we can use a relative path inside our webpack.config:
```
new ManifestPlugin({
fileName: "asset-manifest.json",
publicPath: "~/dist/", <------------------------------------------
generate: (seed, files) => {
const manifestFiles = files.reduce((manifest, file) => { …
```
=> Added support for relative paths (non-root webapplications)

site/jekyll/bundling/webpack.md
Struggled with this for a while, and I couldn't find a reason why "Html.ReactInitJavascript" didn't work.
Saw a post on stackoverflow where "Html.ReactInitJavaScript" was used, and noticed that the S should be uppercase.
=> Changed "Html.ReactInitJavascript" to "Html.ReactInitJavaScript"

src/React.Core/IReactEnvironment.cs, src/React.Core/ReactEnvironment.cs, tests/React.Tests/Core/ReactEnvironmentTest.cs, tests/React.Tests/Mvc/HtmlHelperExtensionsTests.cs
=> Skip adding to _components during ReactWithInit
