reactjs/React.NET

site/jekyll/getting-started/tutorial.md
Result of rebuilding the tutorial app: https://github.com/rickbeerendonk/ReactJS.NET-getting-started-tutorial/tree/1.3
=> Getting started corrections

site/jekyll/getting-started/download.md, src/React.Sample.Cassette/Content/Sample.jsx, src/React.Sample.Mvc4/Content/Sample.jsx, src/React.Sample.Mvc4/Controllers/HomeController.cs, src/React.Sample.Mvc6/Controllers/HomeController.cs, src/React.Sample.Mvc6/wwwroot/js/Sample.jsx, src/React.Sample.Owin/CommentsMiddleware.cs, src/React.Sample.Owin/Content/Sample.jsx, src/React.Sample.Webpack/Content/components/Avatar.jsx
Document still referred to the old filename.
=> Fix name of build batch file & sample avatars

site/jekyll/guides/azure.md
ReactJS.NET version 2.2.0 fixes all issues related to running the V8 JavaScript engine in Azure. I still wrote a brief documentation so that people will know it works and that a version update might be necessary. I also included code to check the available JavaScript engines and how to disable the MSIE engine in case someone is still having problems with V8.
Please feel free to modify the text or fix typos etc. if necessary!
=> Added brief guide for running ReactJS.NET in Azure.

site/jekyll/_layouts/default.html
Updated the copyright year in the footer to be Copyright 2014-2016
=> Update Copyright Year

site/jekyll/getting-started/tutorial.md
Fix issue https://github.com/reactjs/React.NET/issues/259
=> Fix documentation for React 15

src/React.AspNet/HtmlHelperExtensions.cs, src/React.AspNet/HttpContextLifetimeProvider.cs, src/React.AspNet/ReactBuilderExtensions.cs
According to
https://reactjs.net/getting-started/tutorial.html
you run services.AddReact() not app.AddReact()
Fixed exception error messages to match
=> Fixed to to match current setup instructions

src/React.Sample.CoreMvc/React.Sample.CoreMvc.csproj
=> Added TypeScriptToolsVersion=Latest to CoreMvc.csproj

src/React.Core/JavaScriptEngineFactory.cs
=> Added missing Oxford comma to EnsureREactLoaded complaint

site/jekyll/getting-started/tutorial.md
=> updated JSON keys to resolve #586

site/jekyll/getting-started/tutorial.md
Updated keys in CommentBox `handleCommentSubmit` event
=> updated docs to resolve #590

site/jekyll/bundling/weboptimizer.md
Added documentation about setting debug mode in bundling and minification as requested in #633
=> added documentation

src/React.Sample.Mvc4/React.Sample.Mvc4.csproj, src/React.Sample.Mvc4/Web.config, src/React.Sample.Mvc4/packages.config
React.Sample.Mvc4 minor revision updates
update System.Web.Mvc from 4.0.0.0 to v4.0.0.1 (minor)
update Microsoft.AspNet.Mvc from 4.0.30506.0 to 4.0.40804.0 (minor)
=> React.Sample.Mvc4 minor revision updates

src/React.Sample.Webpack.CoreMvc/Startup.cs, src/React.Sample.Webpack.CoreMvc/Views/Home/Index.cshtml, src/React.Sample.Webpack.CoreMvc/package-lock.json, src/React.Sample.Webpack.CoreMvc/package.json, src/React.Sample.Webpack.CoreMvc/webpack.config.js
=> Add vendor bundle to webpack sample

azure-pipelines.yml
=> Fix azure pipelines release builds

site/jekyll/_posts/2019-01-16-4.0.0-release.md
AllowJavaScriptPrecomplilation -> AllowJavaScriptPrecompilation
=> Fix typo in 2019-01-16-4.0.0-release.md

azure-pipelines.yml, src/Cassette.React/Cassette.React.csproj, src/React.AspNet.Middleware/React.AspNet.Middleware.csproj, src/React.AspNet/React.AspNet.csproj, src/React.Core/React.Core.csproj, src/React.MSBuild/React.MSBuild.csproj, src/React.Owin/React.Owin.csproj, src/React.Router.Mvc4/React.Router.Mvc4.csproj, src/React.Router/React.Router.csproj, src/React.Web.Mvc4/React.Web.Mvc4.csproj, src/React.Web/React.Web.csproj, src/System.Web.Optimization.React/System.Web.Optimization.React.csproj
=> Update to .NET Core 3.0 rc1

src/React.Core/package-lock.json, src/React.Sample.Webpack.CoreMvc/package-lock.json
=> Bump webpack dependencies to fix low-risk security warnings

src/React.Core/Exceptions/BabelException.cs, src/React.Core/Exceptions/BabelNotLoadedException.cs, src/React.Core/Exceptions/ReactConfigurationException.cs, src/React.Core/Exceptions/ReactEngineNotFoundException.cs, src/React.Core/Exceptions/ReactException.cs, src/React.Core/Exceptions/ReactInvalidComponentException.cs, src/React.Core/Exceptions/ReactNotInitialisedException.cs, src/React.Core/Exceptions/ReactScriptLoadException.cs, src/React.Core/Exceptions/ReactScriptPrecompilationNotAvailableException.cs, src/React.Core/Exceptions/ReactServerRenderingException.cs, src/React.Core/JavaScriptWithSourceMap.cs, src/React.Core/React.Core.csproj, src/React.Core/SourceMap.cs, src/React.Sample.ConsoleApp/React.Sample.ConsoleApp.csproj
=> Drop netstandard1.6 support

README.md, site/jekyll/_posts/2014-04-04-hello-world.md, site/jekyll/_posts/2014-09-14-1.1.2-release.md, site/jekyll/_posts/2014-11-02-1.1.3-release.md, site/jekyll/_posts/2015-04-13-1.5.0-release.md, site/jekyll/index.md, site/jekyll/tutorials/aspnet4.md, site/jekyll/tutorials/aspnetcore.md
Updated React and React Native URLs
=> Updated links

src/React.Router/ReactRouterComponent.cs, tests/React.Tests/Router/HtmlHelperExtensionsTest.cs
=> Fix query parameter handling

site/jekyll/tutorials/aspnetcore.md
Fixed typo in handleCommentSubmit() for adding new comments, based on CommentModel class data.
=> Update : ASP.NET Core tutorial.md typo
